AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates an Amazon EFS file system and mount target.
Parameters:
  VolumeName:
    Description: The name to be used for the EFS volume
    Type: String
    MinLength: '1'
    Default: myEFSvolume
  VPC:    #Only needed to pass muster until I get the variables provided when the template's launched
    Description: VPC id for where the EFS is going
    Type: String
    MinLength: '1'  
Resources:
  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: True
      FileSystemTags:
      - Key: Name
        Value:
          Ref: VolumeName
  EFSAccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: 
        Ref: FileSystem
      PosixUser:
        Uid: 1000
        Gid: 1000
      RootDirectory:
        CreationInfo: 0755
        Path: /minecraft
  EFSIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupName:
        Fn::GetAtt: [VPC, DefaultSecurityGroup]
      IpProtocol: tcp
      FromPort: "2049"
      ToPort: "2049"
      CidrIp: 0.0.0.0/0
Outputs:
  ServerEFS:
    Description: The EFS id
    Value: 
      Ref: FileSystem
    Export:
      Name: serverEFS
  EFSAccessPoint:
    Description: The EFS access point id
    Value: 
      Ref: EFSAccessPoint
    Export:
      Name: serverEFSAccessPoint
