AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates an Amazon EFS file system and mount target.
Parameters:
  VolumeName:
    Description: The name to be used for the EFS volume
    Type: String
    MinLength: '1'
    Default: myEFSvolume
  MountPoint:
    Description: The Linux mount point for the EFS volume
    Type: String
    MinLength: '1'
    Default: myEFSvolumeMountPoint
  VPC:    #Only needed to pass muster until I get the variables provided when the template's launched
    Description: VPC id for where the EFS is going
    Type: String
    MinLength: '1'  
Resources:
  MountTargetSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VPC
      GroupDescription: Security group for mount target
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 2049 #2049 is nfs port
        ToPort: 2049
        CidrIp: 0.0.0.0/0 #figure out how to get default vpc cidr
  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: True
      FileSystemTags:
      - Key: Name
        Value:
          Ref: VolumeName
  AccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: 
        Ref: FileSystem
      PosixUser:
        Uid: 1000
        Gid: 1000
      RootDirectory:
        CreationInfo: 0755
        Path: /minecraft
  EFSIngress:
    Type: AWS::EC2::SecurityGroupIngress
      Properties:
        GroupName: Fn::Sub:
          - $stuff.DefaultSecurityGroup
          - { stuff: Ref: VPC}
        IpProtocol: tcp
        FromPort: "2049"
        ToPort: "2049"
        CidrIp: 0.0.0.0/0