AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates an Amazon EFS file system and mount target.
Parameters:
  VolumeName:
    Description: The name to be used for the EFS volume
    Type: String
    MinLength: '1'
    Default: myEFSvolume
  MountPoint:
    Description: The Linux mount point for the EFS volume
    Type: String
    MinLength: '1'
    Default: myEFSvolumeMountPoint
  VPC:    #Only needed to pass muster until I get the variables provided when the template's launched
    Description: VPC id for where the EFS is going
    Type: String
    MinLength: '1'
  Subnet: #Only needed to pass muster until I get the variables provided when the template's launched
    Description: Subnet id for where the EFS is going
    Type: String
    MinLength: '1'   
Resources:
  MountTargetSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VPC
      GroupDescription: Security group for mount target
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 2049 #2049 is nfs port
        ToPort: 2049
        CidrIp: 0.0.0.0/0 #figure out how to get default vpc cidr
  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: True
      FileSystemTags:
      - Key: Name
        Value:
          Ref: VolumeName
  # MountTarget:
  #   Type: AWS::EFS::MountTarget
  #   Properties:
  #     FileSystemId:
  #       Ref: FileSystem
  #     SubnetId:
  #       Ref: Subnet
  #     SecurityGroups:
  #     - Ref: MountTargetSecurityGroup
  #   PosixUser:
  #     Gid: 1000
  #     Uid: 1000
  AccessPoint:
    Type: AWS::EFS::AccessPoint
    Properties:
      FileSystemId: !Ref FileSystem
      PosixUser:
        Uid: 1000
        Gid: 1000
      RootDirectory:
        CreationInfo: 0755
        Path: /minecraft



# Outputs:
#   MountTargetID:
#     Description: Mount target ID
#     Value:
#       Ref: MountTarget
#   FileSystemID:
#     Description: File system ID
#     Value:
#       Ref: FileSystem