AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates an Amazon EFS file system and mount target.
Resources:
  efspolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: efs.rw.minecraft-data
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - elasticfilesystem:ClientMount
          - elasticfilesystem:ClientWrite
          - elasticfilesystem:DescribeFileSystems
          Resource: 
            !Join:
              - ''
              - - 'arn:aws:elasticfilesystem:'
                - !Ref: AWS::Region
                - ':'
                - !Ref: AWS::AccountId
                - ':file-system/'
                - !ImportValue: serverEFS
          Condition:
            StringEquals:
              elasticfilesystem:AccessPointArn: 
                !Join:
                  - ''
                  - - 'arn:aws:elasticfilesystem:'
                    - !Ref: AWS::Region
                    - ':'
                    - !Ref: AWS::AccountId
                    - ':access-point/'
                    - !ImportValue: serverEFSAccessPoint
      # Roles:
      #   !Ref <rolename>