# working with steps from: https://docs.docker.com/engine/reference/commandline/run/
# Build when new ver of entrypoint is released: docker build -t joebywan/valheimecswatcher . --no-cache

FROM amazon/aws-cli

# Install jq.  Needed for the watchdog.sh script
RUN yum install -y jq 

#install packages required to build the container
RUN yum install -y tar gzip

# Install nvm, then use that to install npm, ready to install gamedig.  Gamedig's used to query the server
ENV NODE_VERSION=16.14.0
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
RUN node --version
RUN npm --version

# Need this to query the server
RUN npm install gamedig -g

# Clean up before moving on.
RUN yum remove -y tar gzip && \
    package-cleanup -q --leaves | xargs -r -l1 yum -y remove && \
    yum clean all

# Get the monitoring script on the container and set it up to run at start
COPY ./watchdog.sh .

ENTRYPOINT ["./watchdog.sh"]